<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="SteamKit2" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CodigoDeApoyo\**" />
    <Compile Remove="SteamPersonal.SyncWorker\**" />
    <None Remove="CodigoDeApoyo\**" />
    <None Remove="SteamPersonal.SyncWorker\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>